### PR TITLE
Add nroot function

### PR DESCRIPTION
**Pull request by sreyemnayr**
Hey there, I needed an "nth-root" function for something I'm working on so I added it. 
Couldn't sort out how to do 3root27 to be 3. I think that would mean adding another type to the lexer and it was kind of blowing my mind.
Anyway, feel free to merge or not, up to you :)

### CODE REVIEW

**Comment by bugwheels94** [comment]
@sreyemnayr Thanks for making pull request as I thought it became dust. You can get same result using 27 ^ (1/3) though. Let me know if I am wrong

**Comment by sreyemnayr** [comment]
That's exactly what it does. Just for the project I was working on, the strings coming at it would need to be altered to accomodate for those cases, so I'd rather just have it in the evaluator.

**Comment by bugwheels94** [comment]
Unfortunately, root is already a token defined for finding sqrt. Now, I also agree with you. You can do this though without extending and getting exactly what you want.

```
    mexp.addToken([{
        type:2,
        token:"nroot",
        show:"nroot",
        value:function(a,b){
          return Math.pow(a, 1 / b);
        }
    }])

```

Use like: `mexp.eval("27nroot3")` // will give 3

Refer here: http://bugwheels94.github.io/math-expression-evaluator/#extending-tokens

Closing the pull request as it is already part of project

**Comment by bugwheels94** [comment]
Added test for this add token in test file too. Please check

**Pull request closed without merging**
